"""create table db_strikes

Revision ID: 4500a748df98
Revises: 
Create Date: 2023-07-18 14:52:35.117096

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '4500a748df98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
                    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('bio', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id', name='authors_pk')
                    )
    op.create_table('contents',
                    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('body', sa.Text(), nullable=False),
                    sa.Column('status', sa.String(), nullable=False),
                    sa.Column('author_id', sa.ARRAY(postgresql.UUID()), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id', name='contents_pk')
                    )
    op.create_table('contents_authors_association',
                    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('content_id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('author_id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
                    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
                    sa.PrimaryKeyConstraint('content_id', 'author_id'),
                    sa.UniqueConstraint('content_id', 'author_id', name='contents_authors_association_content_id_author_id_key')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contents_authors_association')
    op.drop_table('contents')
    op.drop_table('authors')
    # ### end Alembic commands ###
