"""create table db_strikes

Revision ID: 8264e3d0c425
Revises: 9a18414577e9
Create Date: 2023-07-14 23:23:58.017531

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '8264e3d0c425'
down_revision = '9a18414577e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='authors_pk')
    )
    op.create_table('contents',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='contents_pk')
    )
    op.create_table('contents_authors_association',
    sa.Column('content_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('author_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name='contents_authors_authors_id_fk'),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], name='authors_contents_contents_id_fk'),
    sa.PrimaryKeyConstraint('content_id', 'author_id'),
    sa.UniqueConstraint('content_id', 'author_id', name='contents_authors_association_content_id_author_id_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contents_authors_association')
    op.drop_table('contents')
    op.drop_table('authors')
    # ### end Alembic commands ###
