"""create table db_strikes

Revision ID: 9a18414577e9
Revises: d8a9e18c4ebb
Create Date: 2023-07-14 23:23:11.434486

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '9a18414577e9'
down_revision = 'd8a9e18c4ebb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('contents_authors_association_content_id_author_id_key', 'contents_authors_association', ['content_id', 'author_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contents_authors_association_content_id_author_id_key', 'contents_authors_association', type_='unique')
    # ### end Alembic commands ###
