"""create table db_strikes

Revision ID: a4e641251895
Revises: 
Create Date: 2023-07-14 22:36:25.386915

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = 'a4e641251895'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='authors_pk')
    )
    op.create_table('contents',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='contents_pk')
    )
    op.create_table('contents_authors_association',
    sa.Column('contents_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('authors_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['authors_id'], ['authors.id'], name='contents_authors_authors_id_fk'),
    sa.ForeignKeyConstraint(['contents_id'], ['contents.id'], name='authors_contents_contents_id_fk'),
    sa.PrimaryKeyConstraint('contents_id', 'authors_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contents_authors_association')
    op.drop_table('contents')
    op.drop_table('authors')
    # ### end Alembic commands ###
