"""create table db-strikes

Revision ID: cbd189e03295
Revises: 8264e3d0c425
Create Date: 2023-07-15 14:22:42.134741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cbd189e03295'
down_revision = '8264e3d0c425'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents_authors_association', sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('uuid_generate_v4()'), nullable=False))
    op.add_column('contents_authors_association', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('contents_authors_association', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint('contents_authors_association_content_id_author_id_key', 'contents_authors_association', ['content_id', 'author_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contents_authors_association_content_id_author_id_key', 'contents_authors_association', type_='unique')
    op.drop_column('contents_authors_association', 'updated_at')
    op.drop_column('contents_authors_association', 'created_at')
    op.drop_column('contents_authors_association', 'id')
    # ### end Alembic commands ###
