"""create table db_strikes

Revision ID: d8a9e18c4ebb
Revises: a4e641251895
Create Date: 2023-07-14 23:02:39.945429

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = 'd8a9e18c4ebb'
down_revision = 'a4e641251895'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents_authors_association', sa.Column('content_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('contents_authors_association', sa.Column('author_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.drop_constraint('authors_contents_contents_id_fk', 'contents_authors_association', type_='foreignkey')
    op.drop_constraint('contents_authors_authors_id_fk', 'contents_authors_association', type_='foreignkey')
    op.create_foreign_key('contents_authors_authors_id_fk', 'contents_authors_association', 'authors', ['author_id'], ['id'])
    op.create_foreign_key('authors_contents_contents_id_fk', 'contents_authors_association', 'contents', ['content_id'], ['id'])
    op.drop_column('contents_authors_association', 'contents_id')
    op.drop_column('contents_authors_association', 'authors_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents_authors_association', sa.Column('authors_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('contents_authors_association', sa.Column('contents_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('authors_contents_contents_id_fk', 'contents_authors_association', type_='foreignkey')
    op.drop_constraint('contents_authors_authors_id_fk', 'contents_authors_association', type_='foreignkey')
    op.create_foreign_key('contents_authors_authors_id_fk', 'contents_authors_association', 'authors', ['authors_id'], ['id'])
    op.create_foreign_key('authors_contents_contents_id_fk', 'contents_authors_association', 'contents', ['contents_id'], ['id'])
    op.drop_column('contents_authors_association', 'author_id')
    op.drop_column('contents_authors_association', 'content_id')
    # ### end Alembic commands ###
